Implementing .aar libraries for extensions.
mit-cml/appinventor-sources pull request #2230
Opened 2020-07-03 05:37 UTC by jarlisson2

With this implementation it is possible to add an .aar type library in extension. Just use the existing annotation "@UsesLibraries (libraries ="library.aar ") and add the library to the dependencies, just like the .jar files.

2020-07-03 05:37 UTC, AppInventorWorkerBee commented
Can one of the admins verify this patch?

2020-07-03 14:40 UTC, ewpatton commented
@AppInventorWorkerBee ok to test

2020-08-24 15:20 UTC, ShreyashSaitwal commented
Can this change get staged for nb185?

2020-08-26 19:19 UTC, ewpatton commented
@ShreyashSaitwal This won't go into nb185. We could consider it for nb186. The goal with nb185 is first and foremost to fix issues that cropped up in nb184.

2020-09-05 08:51 UTC, tomer2526 commented
We need to implement this so that we can solve the problem of building this extension: https://community.kodular.io/t/suggestion-for-building-an-extension/77477/15
Please add this in the next update🙏

2020-09-29 15:02 UTC, armandojr1159 commented
Como usar a extensão para checar CNPJ? 
Vi que foi incluído o trecho de tratamento para CNPJ entretanto não consigo a verificação. Está apenas para CPF mesmo?.
Muito bom o seu trabalho. Parabéns

2020-09-30 12:31 UTC, vknow360 approved these changes

2020-10-23 18:46 UTC, joseluu commented
Will the resources contained in the aar end up in the application ?  (as expected)

2021-01-20 15:33 UTC, joseluu commented
Note: I am using this patch on my compilation server, it works, I hope you will integrate it soon.

2022-06-15 03:59 UTC, m-anshuman2166 commented
@ewpatton Any news regarding aar support ?

2024-02-20 07:22 UTC, bigraymasoom commented
Any update on this project?

2024-05-27 19:38 UTC, dhungananikhil approved these changes

2025-02-07 21:02 UTC, ewpatton commented
I've updated this on top of the latest master.

2025-02-25 08:40 UTC, jewelshkjony commented
Would it be possible to merge this change with nb201?

2025-02-25 08:58 UTC, bigraymasoom commented
Yes, please

2025-03-10 03:39 UTC, jewelshkjony approved these changes
I just tested it locally after merging with mit's latest master branch, and it works perfectly with AARs in extensions. ([ref](https://github.com/jewelshkjony/appinventor-sources))

2025-03-11 16:36 UTC, jewelshkjony requested changes
I noticed a bug in ExternalComponentGenerator.java at [#362](https://github.com/mit-cml/appinventor-sources/blob/75980021a49fe6d7fd96b4e64764bd5c8f27f147/appinventor/components/src/com/google/appinventor/components/scripts/ExternalComponentGenerator.java#L362). It is only including the last declared AAR. It should include all declared AARs. This is how I solved ([ref](https://github.com/jewelshkjony/appinventor-sources/commit/acee8542036b85e66c96cf100eeb8a5d389cb799)).

These changes need to be addressed.

2025-08-10 17:00 UTC, jewelshkjony commented
I have identified a problem with the inability to merge JNI/native (.so) libraries.

2025-08-10 17:06 UTC, ewpatton commented
JNI library support is a separate PR.Sent from my iPhoneOn Aug 10, 2025, at 13:00, Jewel Shikder Jony ***@***.***> wrote:﻿jewelshkjony left a comment (mit-cml/appinventor-sources#2230)
I have identified a problem with the inability to merge JNI/native (.so) libraries.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-08-11 09:47 UTC, jewelshkjony commented
It'd be awesome if this [PR](https://github.com/mit-cml/appinventor-sources/pull/2210) also get merged.

2025-08-11 14:24 UTC, bigraymasoom commented
If this feature is merged then libraries related issues will be resolved very much in MIT App inventor ecosystem and will see many modern extensions related to UI and other modern android related features. One thing that i noticed is that assets in libraries( talking about nested assets) in the libraries are not included in the build apk. Also, I suggest that there should be two ways how assets are merged into the apk. First like traditional way, assets are placed under extension package folder in assets folder of apk. Second should be the root folder with nested folders lead to file as many libraries refer to the root folder path like `/assets/org/test/file.js` instead of `/assets/file.js` or in case of extension `/assets/extension.package.name/file.js`.

2025-08-11 14:48 UTC, bigraymasoom commented
There is also another way (again it's just a suggestion) is to place libraries related assets as they are like single file or folder within folder lead to file in the root of assets folder instead of placing them under their extension package name folder. OR we can give users ability in the designer section of App inventor frontend to create the files structure as they like(but again it will not be the scope of this PR but it will solve assets related issues as users can create their own file structures like simple file under assets folder like `/assets/simplefile.js` or in nested structured file path like `/assets/folder_name/simplefile.js`).

2025-08-11 15:45 UTC, jewelshkjony commented
It would be great if this feature also handle merging **assets** and **jni** libraries.
Otherwise, the goal of attaching AAR will remain incomplete!

2025-08-14 18:20 UTC, ewpatton approved these changes
Assets in extensions can always be included using `@UsesAssets`, which has always been true, and there is a separate PR to worry about native libs so I do not think it is worth holding up the release on those grounds.

2025-08-14 18:20 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/scripts/ExternalComponentGenerator.java
> +          copyFile(buildServerClassDirPath + File.separator + library, extensionTempDirPath + File.separator + library);
I recommend restoring the original formatting here for this call as nothing has changed semantically.

2025-08-14 18:20 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/scripts/ExternalComponentGenerator.java
> +          if(library.endsWith(".aar")){
Fix whitespace after `if` and before `{`

2025-08-14 18:20 UTC, ewpatton commented on appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
> +              if (simpleCompTypes.contains(type) || type == "ANDROID") {
Rewrite the latter half of this conditional as `"ANDROID".equals(type)`.

2025-08-14 18:21 UTC, merged

2025-08-14 19:13 UTC, bigraymasoom commented
> Assets in extensions can always be included using `@UsesAssets`

Thanks for merging this Sir. Really appreciated. But assets from aars will not be included in the apk. Build process will just ignore them at appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/AttachCompAssets.java. It's looking for extension assets and during unzipping aar libraries assets will be ignored from asset list.

2025-08-15 06:14 UTC, jewelshkjony commented
> Assets in extensions can always be included using `@UsesAssets`, which has always been true, and there is a separate PR to worry about native libs so I do not think it is worth holding up the release on those grounds.

The `@UsesAssets` annotation includes the assets of an extension under the extension's package name. However, assets included in the AAR file should be placed in the application's root assets directory. This [pull request](https://github.com/mit-cml/appinventor-sources/pull/3555) resolves this issue by merging the assets from the AAR into the application's root directory, and your review of the pull request would be appreciated.