Add new method MoveToPoint for sprites
mit-cml/appinventor-sources pull request #2398
Opened 2021-01-27 05:10 UTC by joysyu

Once I pulled new code, I haven't been able to compile app inventor on my machine :( Since time is limited, could you please help see if this looks ok/works? @ewpatton Thank you so much!

2021-01-27 05:10 UTC, AppInventorWorkerBee commented
Can one of the admins verify this patch?

2021-01-27 06:14 UTC, ewpatton requested changes
In addition to my comments, you'll also need to rebase this onto ucr, e.g.,

```shell
git rebase master --onto ucr
```

If that doesn't work, feel free to come to office hours and we can go over it.

2021-01-27 06:14 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/Sprite.java
> +  public void MoveToPoint(YailList coordinates) {
Annotate this with `@SimpleFunction` so it will show up as a block.

2021-01-27 06:14 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/ImageSprite.java
> +  public void MoveToPoint(YailList coordinates) {
You don't need to override the super here. That's just a trick we use when we want to expose functions on some components but not others.

2021-01-27 06:14 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/Ball.java
> +  public void MoveToPoint(YailList coordinates) {
You don't need to override the super here. That's just a trick we use when we want to expose functions on some components but not others.

2021-01-27 06:14 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
> +  public static final int YOUNG_ANDROID_VERSION = 209;
You don't need to bump `TOUNG_ANDROID_VERSION`. We'll bump it when we actually merge your change.

2021-02-01 14:06 UTC, ewpatton commented
@AppInventorWorkerBee ok to test

2021-02-01 14:06 UTC, ewpatton commented
@joysyu Can you email me your test AIA?

2021-02-01 15:38 UTC, ewpatton approved these changes

2021-02-01 15:44 UTC, merged