Add "every component" block
mit-cml/appinventor-sources pull request #2452
Opened 2021-03-28 16:04 UTC by Vishwas-Adiga

This PR adds an "every component" block that returns a list of all components of a given type.
See [this community topic](https://community.appinventor.mit.edu/t/feature-request-any-all-components/29567) for more context.

Screenshots:
![image](https://user-images.githubusercontent.com/28251020/112758659-11a60680-900d-11eb-9085-9f45686594d6.png)
![image](https://user-images.githubusercontent.com/28251020/112758664-19fe4180-900d-11eb-9861-9406b777fd70.png)

2021-03-31 15:24 UTC, ewpatton commented
@Vishwas-Adiga This is a good start, but since it changes the blocks that are available in the companion, you should rebase the change onto `ucr`, bump the `BLOCKS_LANGUAGE_VERSION` in YaVersion, and add an upgrade path in versioning.js. From a design perspective, what other designs did you consider and why do you think this approach is the best option?

2021-03-31 17:38 UTC, Vishwas-Adiga commented
Thanks for the pointers, @ewpatton . I'll make the required changes this weekend

I'll also try and link to a design document outlining how I came to this block design for the required functionality, if such an arrangement works for you?

2021-03-31 17:40 UTC, ewpatton commented
@Vishwas-Adiga Yes that's fine.

2021-05-14 12:29 UTC, ewpatton requested changes
Thanks @Vishwas-Adiga. This looks pretty good. Please merge `ucr` to pick up @BeksOmega's changes and there are a few minor things to address, but otherwise this looks pretty good to me.

2021-05-14 12:29 UTC, ewpatton commented on appinventor/blocklyeditor/src/generators/yail/componentblock.js
> +Blockly.Yail.component_all_component_block = function() {
For forwards compatibility, please switch this to `Blockly.Yail['component_all_component_block']`

2021-06-10 19:00 UTC, Vishwas-Adiga commented
Sorry, I've been unable to work on this lately. I'll work on the style changes and bring the branch up to date right away

2023-02-03 22:25 UTC, ewpatton approved these changes

2023-02-04 07:08 UTC, merged