New test Class for Label Component
mit-cml/appinventor-sources pull request #2457
Opened 2021-04-02 04:57 UTC by preetvadaliya

This PR adds new test cases class for **Label** component.

### `ant tests` Result for LabelTest.java
![Capture](https://user-images.githubusercontent.com/80121827/113381970-eff6a780-939d-11eb-88c3-383cf358a48a.PNG)

Thank you
Preet Vadaliya

2021-04-02 04:57 UTC, AppInventorWorkerBee commented
Can one of the admins verify this patch?

2021-04-07 12:45 UTC, ewpatton commented
@AppInventorWorkerBee ok to test

2021-04-08 19:26 UTC, SusanRatiLane requested changes
Changes requested in PR comment.

2021-04-09 16:37 UTC, preetvadaliya commented
@SusanRatiLane thank you for your compliment.

As per your suggestion I added 2 new test cases for setHeightPercent and setWidthPercent. 

But I am still exploring in HTMLFormat.

2021-05-11 17:50 UTC, SusanRatiLane requested changes
The rest of the tests should get the same changes you made in your last commit. Rather than setting a parameter and verifying the parameter is set correctly, test to be sure that the textview is correct.

2021-05-13 18:33 UTC, preetvadaliya commented
@SusanRatiLane 

I am a bit confused as to what you are pointing me for changes, but let me clarify what I have done,
whenever the test case started executing the `SetUp()` method will be called and it will create a new Label into Form and textView is cast from the newly created Label so I think we not required to test whether the textview is correct or not.

2021-05-25 13:43 UTC, SusanRatiLane requested changes
Most of the tests look good, but a couple still need checks against the textview

2021-05-25 13:43 UTC, SusanRatiLane commented on appinventor/components/tests/com/google/appinventor/components/runtime/LabelTest.java
> +  }
This test needs a check against the textView

2021-05-25 13:43 UTC, SusanRatiLane commented on appinventor/components/tests/com/google/appinventor/components/runtime/LabelTest.java
> +  }
The false test for HTMLFormat is correct, but the true test needs a check against the textView

2021-05-25 17:36 UTC, preetvadaliya commented
@SusanRatiLane Thanks for your Suggestions.

I just made some changes according to your suggestion if these test cases are okay then I will update my other PRs according to this.

2021-05-25 20:32 UTC, SusanRatiLane approved these changes
Looks good. I think this is ready to merge.

2021-05-25 20:32 UTC, merged