Fix 2447
mit-cml/appinventor-sources pull request #2487
Opened 2021-05-17 19:03 UTC by jingmiao-z

split method, delete "" first empty string.

2021-05-17 19:03 UTC, AppInventorWorkerBee commented
Can one of the admins verify this patch?

2021-05-17 19:03 UTC, ewpatton commented
@AppInventorWorkerBee ok to test

2021-06-04 14:38 UTC, ewpatton requested changes

2021-06-04 14:38 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/util/JavaStringUtils.java
> +  public static List<String> split(String text, String at){
To address the broken test, we should change the return type here to YailList and then call YailList.makeList(...) to wrap the output of this function as a YailList.

2021-06-10 21:56 UTC, ewpatton commented
Still need to test on SDK versions pre-26 and the latest SDK.

2023-02-04 19:19 UTC, ewpatton approved these changes

2023-02-04 19:19 UTC, merged