ListView documentation updates
mit-cml/appinventor-sources pull request #2513
Opened 2021-07-23 18:59 UTC by SusanRatiLane

Updates to documentation for the new ListView with advanced layouts.

2021-07-29 22:15 UTC, ellelili2025 commented on appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
>     *              {@link Component#HORISONTAL_ORIENTATION},
Is this also supposed to be HORIZONTAL instead of HORISONTAL?

2021-07-29 22:18 UTC, ellelili2025 requested changes
A small typo change is needed.

2021-07-30 14:15 UTC, SusanRatiLane commented
Heh. This is a Britishism. I updated it several places but apparently missed some.

2021-08-17 14:08 UTC, ellelili2025 commented
@ewpatton  Since Susan is out of town, I will make the trivial change and merge it. Do you want to take one more look?

2021-08-17 14:43 UTC, ewpatton commented
@ellelili2025 That'd be great thanks. Please also resolve the merge conflict in the userinterface documentation.

2021-08-17 16:39 UTC, ellelili2025 approved these changes

2021-08-17 16:55 UTC, merged