Web component's broken tooltips fixes
mit-cml/appinventor-sources pull request #2614
Opened 2021-12-01 11:35 UTC by preetvadaliya

This PR fix issue #2445.

2021-12-01 11:35 UTC, AppInventorWorkerBee commented
Can one of the admins verify this patch?

2021-12-01 11:53 UTC, preetvadaliya commented
@ewpatton sir,

After the changes, I compared `simple_components.json` for both versions of `ComponentProcessor.java`, but there are no additional changes, instead of the tooltip changes to the "DataChanged" event.

2021-12-01 18:49 UTC, SusanRatiLane requested changes
Small text change.

2021-12-01 18:49 UTC, SusanRatiLane commented on appinventor/components/src/com/google/appinventor/components/runtime/CloudDB.java
> +      "`tag` that has been updated and the `value` it now has.")
This wording might lead people think that this event launches another event.

I'd recommend: "Event indicating that CloudDB data has changed for the given tag and value."

2021-12-01 18:49 UTC, SusanRatiLane commented on appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
> +        this.description = description.split("[@|{@]+(([a-zA-Z])*)+[(\\s)*]")[0].trim();
This seems to test correctly. I'd like to ask another dev to take a look as a sanity check.

2021-12-01 18:59 UTC, SusanRatiLane commented
@AppInventorWorkerBee  ok to test

2021-12-03 21:20 UTC, SusanRatiLane commented
@AppInventorWorkerBee ok to test.

2021-12-07 19:13 UTC, ewpatton commented
@AppInventorWorkerBee retest this please

2022-01-04 21:12 UTC, SusanRatiLane approved these changes

2022-01-04 21:12 UTC, merged