Allow extension option list enums to not have fromUnderlyingValue method
mit-cml/appinventor-sources pull request #2731
Opened 2022-09-08 18:27 UTC by shreyashsaitwal

Currently, the component processor requires every component, including extensions, to have a static method `fromUnderlyingValue` in their option-list helper enums. The purpose of this method is to help maintain backward compatibility when migrating old components (or extensions) to use the newly introduced helpers, however, it doesn't make sense to force new components and extensions to have it.

This PR lifts this restriction from every extension. Option list helpers of built-in components, i.e., the ones that reside under the `com.google.appinventor.components` package still need to have the `fromUnderlyingValue` static method.

2022-09-08 18:27 UTC, AppInventorWorkerBee commented
Can one of the admins verify this patch?

2022-09-13 16:06 UTC, ewpatton commented
@AppInventorWorkerBee ok to test

2022-09-15 17:33 UTC, ewpatton requested changes

2022-09-15 19:44 UTC, ewpatton approved these changes

2022-09-15 19:45 UTC, merged