Add "RemoveItemAtIndex" block to ListView
mit-cml/appinventor-sources pull request #2789
Opened 2022-12-26 20:37 UTC by devarsh-mavani-19

See issue #2782
I have created a @simplefunction in listview component.

2022-12-26 20:37 UTC, AppInventorWorkerBee commented
Can one of the admins verify this patch?

2023-01-03 15:33 UTC, ewpatton requested changes

2023-01-03 15:33 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
> +  private int fontTypeDetail;
I'm not clear why this change is necessary to satisfy the request.

2023-01-03 15:33 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
> +   */
You can move the description below into the Javadoc and the documentation generator should take care of the rest.

2023-01-03 15:33 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
> +      }
Make sure that this logic keeps the two lists in sync. We don't want to remove an element at one index if it has a corresponding representation at the same index in the other list.

2023-01-03 15:33 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
> +  public int FontTypeface() {
Unrelated change.

2023-01-03 15:33 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
> +  public void FontTypeface(int typeface) {
Unrelated change.

2023-01-03 15:33 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
> +  public int FontTypefaceDetail() {
Unrelated change.

2023-01-03 15:33 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
> +  public void FontTypefaceDetail(int typeface) {
Unrelated change.

2023-01-03 15:35 UTC, ewpatton commented
@devarsh-mavani-19 In addition to my comments, you'll also want to bump the version number of the ListView component in YaVersion.java, then implement the (trivial) upgraders in YoungAndroidFormUpgrader.java and versioning.js

2023-01-03 15:35 UTC, ewpatton commented
@AppInventorWorkerBee ok to test

2023-01-04 13:20 UTC, devarsh-mavani-19 commented
> @ewpatton when i ran this feature in app, it is throwing an exception that "YailList does not implement removePosRange" I checked the super class of YaiList i.e. AbstractSequence.java (in kawa source code). The remove method is calling removePosRange method which throws unsupported exception. So do I need to implement the remove method in YailList from scratch or is there already kawa based function that i can use in java?
> 
> edt: 1 more way i can think of is to convert the Yailist to array using the toArray method and then remove item at index from array and recreate the list using makeList method (of Yailist class). But i think this will not be efficient.

@ewpatton do i have to implement removePosRange function in kawa as well or I just have to implement it directly in YailList.java? And which approach from above comment should I go for?

2023-01-11 19:41 UTC, devarsh-mavani-19 commented
@ewpatton can you please have look at above comment?

2023-01-11 20:26 UTC, ewpatton commented
I think it might make more sense to change the type of `stringItems` from being a `YailList` to a regular `List`. I don't think there's a reason to keep the internal type as YailList, which is mainly used for content manipulated by the blocks.

2023-01-11 20:57 UTC, halatmit commented
sounds reasonable

== Hal

Hal Abelson
***@***.***
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.



On Wed, Jan 11, 2023 at 3:26 PM Evan W. Patton ***@***.***>
wrote:

> I think it might make more sense to change the type of stringItems from
> being a YailList to a regular List. I don't think there's a reason to
> keep the internal type as YailList, which is mainly used for content
> manipulated by the blocks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mit-cml/appinventor-sources/pull/2789#issuecomment-1379443325>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGAXN5CTNPPQPCLS3BD2Y3WR4JO7ANCNFSM6AAAAAATJ4EM2Y>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-01-16 06:20 UTC, devarsh-mavani-19 commented
> I think it might make more sense to change the type of `stringItems` from being a `YailList` to a regular `List`. I don't think there's a reason to keep the internal type as YailList, which is mainly used for content manipulated by the blocks.

@ewpatton Have converted YailList to List<String> can you please check this. I haven't refactored some existing functions like 
`elements`, `selectionIndex`, `setSelectionFromIndex`, `setSelectedIndexFromValue` because they were used by other components. So instead I just changed it as per my the requirements of ListView in a new method.

2023-02-13 04:50 UTC, devarsh-mavani-19 commented
I have converted YailList to java list. Please can u review it?
Thanks

2023-04-29 14:09 UTC, ewpatton requested changes

2023-04-29 14:09 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
> +        stringItems = ElementsUtil.elementsStrings(itemsList, "Listview");
We should fix the misspelling of "Listview" to "ListView"

2023-04-29 14:09 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/util/ElementsUtil.java
There are a number of code style errors in this file. You can run `ant -Dcommit=ucr checkstyle` to have it check the code, but mostly it looks like you've missed putting whitespace before an opening curly brace. For future reference we follow the Google Java Style guide.

2023-04-29 14:10 UTC, ewpatton commented
@devarsh-mavani-19 There are a few more things that need to be done to get this ready to merge since you're adding a new block:

1. Update the LISTVIEW_COMPONENT_VERSION field of YaVersion by 1 and note the addition of the new block
2. In YoungAndroidFormUpgrader, add a check for the previous version number and update it to the new version. No change is needed.
3. In versioning.js, add the new version number and indicate that no upgrade to the blocks is necessary.

2023-09-25 18:47 UTC, ewpatton commented
@devarsh-mavani-19 We'd like to get this into the next App Inventor release. Do you think you could address the earlier feedback this week, or should one of the core devs adopt it?

2023-10-16 14:30 UTC, ewpatton commented
@gordonlu310 Also, after thinking about it I think that the SetCursorAt() function should be 1-indexed rather than 0-indexed, so we will need to subtract 1 from the incoming index. This will make use of this function compatible with the text blocks without requiring the user to do additional computations. For example:

<img width="567" alt="blocks (83)" src="https://github.com/mit-cml/appinventor-sources/assets/1331253/6a1c2209-60e9-4d15-b312-08b029e19e0e">

If in the TextBox1 you put "abcdefg" and then search for "cde" the cursor will end up between the "c" and "d", whereas it seems like it should show up at the start of "cde".

2023-10-16 15:20 UTC, ewpatton approved these changes

2023-10-16 16:34 UTC, merged