removing-deprecated-cache-code
mit-cml/appinventor-sources pull request #2807
Opened 2023-01-20 15:13 UTC by adirn26

Fixes: https://github.com/mit-cml/appinventor-sources/issues/1830
Removed depricated DrawingCache functions 
Updated variables accordingly

2023-01-20 15:13 UTC, AppInventorWorkerBee commented
Can one of the admins verify this patch?

2023-02-09 23:17 UTC, ewpatton commented
@AppInventorWorkerBee ok to test

2023-03-30 10:43 UTC, ewpatton requested changes
Two minor things to address.

2023-03-30 10:43 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java
> +        return currentBitmap;
Please fix the indentation here. Our code style is to indent a new scope by 2 spaces only.

2023-03-30 10:43 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java
> +      // Check the complete bitamp.
bitamp => bitmap

2023-03-30 17:50 UTC, adirn26 commented
Fixed Indentation and Typo

2023-08-18 00:39 UTC, ewpatton approved these changes
LGTM, but I need to rebase it onto ucr before merging.

2023-08-18 01:21 UTC, merged