Visual accessibility
mit-cml/appinventor-sources pull request #2862
Opened 2023-03-28 16:33 UTC by daki7711

This address the visibility features for iOS

2023-03-28 17:10 UTC, ewpatton requested changes
Note that currently CheckBox and Switch are not marked as AccessibleComponent, so if you set the BigText property in the blocks, those components will not update.

2023-03-28 17:10 UTC, ewpatton commented on appinventor/components-ios/src/Form.swift
> +    HighContrast = false
Since properties are typically set in order by the Scheme code, we should sort these accordingly among the above code.

2023-03-28 17:10 UTC, ewpatton commented on appinventor/components-ios/src/Label.swift
> +  @objc func updateFontSize() {
This does not need to be marked as `@objc` as it won't be called directly from Scheme.

2023-03-28 17:10 UTC, ewpatton commented on appinventor/components-ios/src/Switch.swift
> +      //_text.font = UIFont(descriptor: _text.font.fontDescriptor, size: CGFloat(size))
Remove commented out code.

2023-03-28 17:10 UTC, ewpatton commented on appinventor/components-ios/src/Switch.swift
> +  @objc func updateFontSize() {
See earlier notes about use of `@objc`

2023-03-28 17:10 UTC, ewpatton commented on appinventor/components-ios/src/TextBox.swift
> +  @objc open var placeholderColor: Int32 {
Since this is something internal it does not need to be marked `@objc`

2023-03-28 17:10 UTC, ewpatton commented on appinventor/components-ios/src/TextBoxBase.swift
> +  @objc func updateFontSize() {
Remove `@objc`

2023-03-28 17:10 UTC, ewpatton commented on appinventor/components-ios/src/TextBoxBase.swift
> +  @objc func updateColor() {
Remove `@objc`

2023-03-28 17:10 UTC, ewpatton commented on appinventor/components-ios/src/TextBoxBase.swift
> +        _delegate.font = getFontSize(font: _delegate?.font, size: kFontSizeLargeDefault) ?? _delegate.font
I don't think you need the optional chaining here for `_delegate`

2023-03-28 17:10 UTC, ewpatton commented on appinventor/components-ios/src/TextBoxBase.swift
> +    }
Review optional chaining here.

2023-03-28 17:25 UTC, daki7711 commented on appinventor/components-ios/src/AccessibleComponent.swift
> +//
I don't recall creating this, I think it was created automatically maybe I'm wrong. But what is the open source version?

2023-03-29 19:50 UTC, daki7711 commented on appinventor/components-ios/src/TextBoxBase.swift
> +    }
what should I do here?

2023-03-30 19:35 UTC, daki7711 commented on appinventor/components-ios/src/Image.swift
> +
I don't get it, I erased this and it also is gone in my code, but not sure why it's stays here

2023-04-11 19:17 UTC, SusanRatiLane approved these changes
This tests out.

2023-04-11 21:05 UTC, ewpatton approved these changes

2023-04-11 21:14 UTC, merged