Allow filtering components in source structure
mit-cml/appinventor-sources pull request #2898
Opened 2023-06-04 16:31 UTC by barreeeiroo

This PR allows app developers to filter the source structure (_components tree_) by component type (all, visible and non-visible). This change is brought from Kodular sources.

![image](https://github.com/mit-cml/appinventor-sources/assets/19251112/4c28c9c4-f267-43e5-857d-aa28dc7d0232)

2023-09-12 01:44 UTC, ewpatton commented
@barreeeiroo @SusanRatiLane I have rebased this onto master now that the UI binder refactor has been merged. Tested both the classic and new forms. It works but I'm not super excited about having to pass the parent to the child so that the child can manipulate the parent. We'll have to think about that more.

2023-10-11 16:09 UTC, SusanRatiLane requested changes
We're hoping to have PRs approved on Monday. Let us know if you'll be unable to look at it.

2023-10-18 16:09 UTC, merged

2023-10-24 20:00 UTC, SusanRatiLane commented on appinventor/appengine/src/com/google/appinventor/client/explorer/SourceStructureExplorer.java
>      panel.setCellHorizontalAlignment(buttonPanel, HorizontalPanel.ALIGN_CENTER);
> This was not commented out, the comment was there as in Kodular we have a toolbar with these buttons. There was the TODO comment to move them somewhere else.

Yes, it looks like I removed the buttons along with the comments. I'll put up a PR to fix the regression.

The intent of the TODO comment is still not clear to me.

2023-10-24 20:00 UTC, barreeeiroo commented on appinventor/appengine/src/com/google/appinventor/client/explorer/SourceStructureExplorer.java
>      panel.setCellHorizontalAlignment(buttonPanel, HorizontalPanel.ALIGN_CENTER);
I'm working on it already, don't worry.