Corrected spelling error of the documentation of BluetoothClient: frue → true
mit-cml/appinventor-sources pull request #2939
Opened 2023-08-08 12:54 UTC by GordonL0049

Corrected issue [#2938](https://github.com/mit-cml/appinventor-sources/issues/2938) in this PR. Changes:

- Correct the typo from `frue` to `true` in two files.

2023-08-08 12:54 UTC, AppInventorWorkerBee commented
Can one of the admins verify this patch?

2023-08-08 13:52 UTC, ewpatton commented
@GordonL0049 Note that the HTML is built from the Markdown versions of the files. You need to make sure that the Markdown also reflects the fix.

2023-08-08 16:53 UTC, ewpatton requested changes
Once the Markdown file has been updated this should be good to go.

2023-08-08 23:43 UTC, GordonL0049 commented
Done, but when I review the changes, I found myself accidentally `Merge branch 'mit-cml:master' into master` ... is it OK to leave it there? If not, is there a way for me to remove it?

2023-08-09 14:22 UTC, ewpatton commented on appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockForm.java
> +      }
Revert this change.

2023-08-09 14:26 UTC, ewpatton commented
I would recommend in the future doing your development on a branch started from master (or ucr, as appropriate), rather than on the branch directly. When we merge a change, we will create a single logical commit using a squash merge into the base branch. If you do your development directly on base branch this will cause your copy to end up out of sync with the MIT copy.

2023-08-10 23:05 UTC, GordonL0049 commented
Already updated. Does it look OK?

2023-08-11 12:36 UTC, ewpatton approved these changes

2023-08-11 12:58 UTC, merged