Feature/default file scope
mit-cml/appinventor-sources pull request #2943
Opened 2023-08-09 19:50 UTC by axz0315

Began DefaultFileScope implementation in ios. Created a new folder in components called common that contains two new files: FileScope and OptionList.

2023-08-09 19:50 UTC, AppInventorWorkerBee commented
Can one of the admins verify this patch?

2023-09-11 19:59 UTC, ewpatton requested changes

2023-09-11 19:59 UTC, ewpatton commented on appinventor/components-ios/src/FileScope.swift
> +//
Update the copyright preamble to match other Swift files.

2023-09-11 19:59 UTC, ewpatton commented on appinventor/components-ios/src/FileScope.swift
> +public class FileScope: OptionList {
We should double check, but I think this needs to be annotated `@objc` so that it can be visible to the Scheme side.

2023-09-11 19:59 UTC, ewpatton commented on appinventor/components-ios/src/Form.swift
> +
Remove excess whitespace introduced here.

2023-09-11 19:59 UTC, ewpatton commented on appinventor/components-ios/src/Form.swift
> +  fileprivate var _defaultFileScope: fileScope.App //declare vs define
Shouldn't this be `_defaultFileScope = FileScope.App`?

2023-09-11 19:59 UTC, ewpatton commented on appinventor/components-ios/src/Sprite.swift
> +
These changes are from your other PR and are not relevant to this PR. We should clean up the branch before merging.

2023-09-11 19:59 UTC, ewpatton commented on appinventor/components-ios/src/OptionList.swift
> +//
Update copyright preamble to match other Swift files.

2023-09-11 19:59 UTC, ewpatton commented on appinventor/components-ios/src/Form.swift
> +  fileprivate var _defaultFileScope: fileScope.App //declare vs define
Also, you need to implement the getter/setter pair for exposing this to other components and the designer.

2023-11-09 22:52 UTC, ewpatton commented
@AppInventorWorkerBee ok to test

2023-11-13 17:52 UTC, ewpatton approved these changes
LGTM

2023-11-13 17:53 UTC, merged