Fix Error Handling in ChatBot and ImageBot
mit-cml/appinventor-sources pull request #2984
Opened 2023-09-08 16:24 UTC by jisqyv

Properly pass through the HTTP Status code from the Chat/Image Bot proxy

Change-Id: I35c2852dec19ad7bdd4a61dab47e771783209614

2023-09-08 16:26 UTC, jisqyv commented
Note: Changed ImageException to subclass Exception instead of IOException. Otherwise the exception thrown on line 567 is caught on line 569!

2023-09-11 15:51 UTC, ewpatton reviewed
Two comments for us to think about but otherwise LGTM.

2023-09-12 14:36 UTC, jisqyv commented on appinventor/components/src/com/google/appinventor/components/runtime/ImageBot.java
>            FileOutputStream out = new FileOutputStream(outFile);
@ewpatton Is try-with-resource implemented in the JVM on phones? Because that is an obvious thing to use here.

2023-09-12 14:49 UTC, jisqyv commented on appinventor/components/src/com/google/appinventor/components/runtime/ImageBot.java
>            FileOutputStream out = new FileOutputStream(outFile);
@ewpatton Never mind, I just used a standard try-finally block

2023-09-12 14:49 UTC, jisqyv commented on appinventor/components/src/com/google/appinventor/components/runtime/ChatBot.java
> +    int responseCode = 500;   // A reasonable default
Updated

2023-09-12 15:18 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/ImageBot.java
>            FileOutputStream out = new FileOutputStream(outFile);
Only for Android N and later. For earlier versions you still need to use a standard try-finally.

2023-09-12 16:38 UTC, ewpatton requested changes

2023-09-12 16:38 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/ChatBot.java
> +    int responseCode = 500;   // A reasonable default
It seems this was only changed for ImageBot and not ChatBot.

2023-09-14 15:51 UTC, jisqyv commented
@ewpatton Yes it was. Check line 545 in ImageBot.java

2023-09-14 15:54 UTC, ewpatton commented
I guess I am confused why it was changed for ImageBot but not ChatBot. Wouldn't we want ChatBot to also report -1 if a connection couldn't be established?

2023-09-14 16:56 UTC, jisqyv commented
@ewpatton Oops, just fixed ChatBot

2023-09-14 17:00 UTC, ewpatton approved these changes
LGTM

2023-10-11 15:22 UTC, merged