add docker file
mit-cml/appinventor-sources pull request #3229
Opened 2024-08-26 18:52 UTC by ronknight

2024-08-26 18:52 UTC, AppInventorWorkerBee commented
Can one of the admins verify this patch?

2024-08-29 18:13 UTC, ewpatton requested changes

2024-08-29 18:13 UTC, ewpatton commented on .devcontainer/Dockerfile
> +    apt-get install -y openjdk-8-jdk curl python3 python3-pip && \
Starting in October we will no longer be deploying with Java 8. This should be changed to Java 11.

2024-08-29 18:13 UTC, ewpatton commented on .devcontainer/Dockerfile
> +FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu
Is there a reason to use this container versus the official Ubuntu image?

2026-05-05 15:36 UTC, josmas commented
Closing this for now. Feel free to reopen and address comments. Thanks!

2026-05-05 15:36 UTC, closed without merging