ListView Android performance refactor
mit-cml/appinventor-sources pull request #3235
Opened 2024-09-09 18:23 UTC by SusanRatiLane

General items:
- [X] `ant tests` passes on my machine

- [X] I branched from `ucr`
- [X] My pull request has `ucr` as the base

Further, if you've changed the blocks language or another user-facing designer/blocks API (added a SimpleProperty, etc.):

- [ ] I have updated the corresponding version number in YaVersion.java
- [ ] I have updated the corresponding upgrader in YoungAndroidFormUpgrader.java (components only)
- [ ] I have updated the corresponding entries in versioning.js

^^ I have actually never done this, so we'll need to talk.

*Description*

This is a performance refactor submitted by @patryk84a in February 2024. He also included some methods for adding and removing items that the class should probably have. I included implementations for these in iOS. 

He also included one aesthetic property for which I included a stub for iOS.

Fixes #2857 

Co-author: @patryk84a

2024-09-10 15:24 UTC, SusanRatiLane commented
Hmm. I thought the tests were passing, but two ListView ones are not. Patryk's changes have broken an assumption the tests are making, but I'm trying to sort out what it is.

2024-09-13 08:13 UTC, patryk84a commented
The HintSearchText property has been removed. Maybe instead for Android add a fixed hint text but from the Android resources "@android:string/search_go", then we should get the string in the language set in the phone, without the possibility of defining your own, which would be compatible with IOS

2024-09-13 15:10 UTC, SusanRatiLane commented
> The HintSearchText property has been removed. Maybe instead for Android add a fixed hint text but from the Android resources "@android:string/search_go", then we should get the string in the language set in the phone, without the possibility of defining your own, which would be compatible with IOS

Actually, that was removed because someone else wrote a PR that adds the property for both Android and iOS. I should probably have mentioned that in the PR description.

2024-09-16 03:08 UTC, ewpatton requested changes
In addition to the file level and inline comments, the LISTVIEW_COMPONENT_VERSION value in YaVersion needs to be bumped to the change in the properties, and the appropriate code paths in YoungAndroidFormUpgrader.java and versioning.js need to be added.

2024-09-16 03:08 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/common/ListOrientation.java
Line endings.

2024-09-16 03:08 UTC, ewpatton commented on appinventor/components/src/com/google/appinventor/components/runtime/ListBounceEdgeEffectFactory.java
Line endings need to be switched to Unix. There are also a few indentation/wrapping issues that IntelliJ should be able to help with.

2024-09-17 11:31 UTC, patryk84a commented
I guess I can't make any changes here, right?

2024-09-18 01:10 UTC, SusanRatiLane commented
> I guess I can't make any changes here, right?

I should be able to give you access. I'll take a look.

2024-09-19 18:22 UTC, SusanRatiLane commented on appinventor/components/src/com/google/appinventor/components/common/LayoutType.java
> +   LayoutType(int value) {
> This seems like it should be private. The indentation is also off by 1.

IntelliJ informs me that private is redundant for enum constructions.

2024-09-19 18:29 UTC, SusanRatiLane commented on appinventor/components/src/com/google/appinventor/components/common/ListOrientation.java
> +  ListOrientation(int value) {
Ditto for redundant.

2024-10-31 01:20 UTC, patryk84a commented
Fix duplicate call to notifyDataSetChanged - I don't really understand this fix because I didn't find a duplicate call to the notifyDataSetChanged() method. How is it supposed to help to place this method in several places instead of in the clearSelection() function, since this function is called anyway. 

Any syntax errors, whitespace, etc. were caused by working in an editor without intelij. I think my current code editor would catch those errors now. It's great that there are public methods related to Multiselect. We'll be able to use it in the extension. 

I tried to reflect the appearance of the new list view in the Mock file in gwt, but I can't make these components behave the way I want them to. The problem is probably with automatic dimensioning, e.g. to the width of the parent, etc. In gwt, I think you have to give everything in constant calculated dimensions.

2024-11-01 01:04 UTC, patryk84a commented
Ok, I tested it and it seems to work fine. There is one small detail that I didn't notice before. There is no margin between the image and the text. The text is glued directly to the image. I think a quick fix is ​​to add a margin to the right of the image, then it will work for every layout.

layoutParamsImage.setMargins(0, 0, 15, 0);

The padding for the element is set to 15, so I think the margin can also be set to 15 so there will be equal space around the image.

2024-11-05 20:45 UTC, jisqyv commented
I just pushed up the squashed version, after merging in ucr

2024-11-05 21:36 UTC, jisqyv requested changes
So, Everything appears to work in the Companion, but if I compile an App, on my Samsung phone running Android 14, the filter bar does not show up!

2024-11-05 21:39 UTC, jisqyv commented
Additional info. The filter bar *is* there, but it has a black background, while with the companion, the background was white.

2024-11-05 22:51 UTC, jisqyv commented
I'm removing my objections. The behavior I'm seeing (black search bar) is also present in our current production system, so this is not a new bug.

2024-11-05 22:52 UTC, jisqyv approved these changes
LGTM

2024-11-06 15:55 UTC, ewpatton approved these changes
LGTM

2024-11-06 15:57 UTC, ewpatton commented
Note that I had previously fixed those comments in the individual changes prior the squash.

2024-11-06 18:54 UTC, patryk84a commented
Is it possible to make the small correction I mentioned before the release, i.e. the margin on the right side of the image? Now the text "touches" the image in an unsightly way. I also mentioned the black background of the search bar in the community thread, apparently no one reads the comments posted there, but this can be left for the next ListView correction.

2024-11-06 19:05 UTC, patryk84a commented
> Additional info. The filter bar _is_ there, but it has a black background, while with the companion, the background was white.

Yes, I've noticed that too. The theme type auto-detection doesn't work very well. One idea was to set the EditText background to transparent so that it takes the ListView background, and set the search text color to the MainText color. If the app author sets the ListView colors to the appropriate ones, the search bar will also have the appropriate colors. We don't have to decide the colors for the app author.

2024-11-07 15:23 UTC, merged