Fixed iOS DismissProgressDialog Issue
mit-cml/appinventor-sources pull request #3267
Opened 2024-11-27 01:56 UTC by ghu999

General items:

- [ ] I have updated the relevant documentation files under docs/
- [ ] My code follows the:
    - [ ] [Google Java style guide](https://google.github.io/styleguide/javaguide.html) (for .java files)
    - [ ] [Google JavaScript style guide](https://google.github.io/styleguide/jsguide.html) (for .js files)
- [ ] `ant tests` passes on my machine

If your code changes how something works on the device (i.e., it affects the companion):

- [ ] I branched from `ucr`
- [ ] My pull request has `ucr` as the base

Further, if you've changed the blocks language or another user-facing designer/blocks API (added a SimpleProperty, etc.):

- [ ] I have updated the corresponding version number in YaVersion.java
- [ ] I have updated the corresponding upgrader in YoungAndroidFormUpgrader.java (components only)
- [ ] I have updated the corresponding entries in versioning.js

For all other changes:

- [ ] I branched from `master`
- [ ] My pull request has `master` as the base

What does this PR accomplish?

Adds a CustomAlertView array to allow for handling of multiple dialogs. Before, the Dismiss progress dialog would not even appear on top of the choose dialog. Now, both work as intended based on the given app code; the dismiss dialog dismisses after 3 seconds and the choose dialog correctly cancels when clicked.

Fixes #3218.

Resolves # .

2024-11-27 01:56 UTC, AppInventorWorkerBee commented
Can one of the admins verify this patch?

2024-11-27 14:23 UTC, SusanRatiLane commented
@AppInventorWorkerBee OK to test.

2024-11-27 18:02 UTC, SusanRatiLane requested changes

2024-11-27 18:02 UTC, SusanRatiLane commented on appinventor/appengine/src/com/google/appinventor/client/style/neo/neo.css
> +    flex-shrink: 0;
You have correctly pointed this PR to ucr, but you branched from master. Therefore the diff has changes from master that are not currently in ucr. You need to also branch from ucr.

2024-11-27 18:57 UTC, ghu999 commented on appinventor/components-ios/src/Notifier.swift
> +//  }
yes i did.

2024-11-27 19:48 UTC, SusanRatiLane commented on appinventor/components-ios/src/Notifier.swift
> +//  }
> yes i did.

OK, if the code is not being used, it should be removed.

2024-12-11 18:58 UTC, ewpatton approved these changes
LGTM

2024-12-11 18:58 UTC, merged